version: "3.8"

services:
  bot:
    build: .
    container_name: tg_quest_bot
    restart: always
    env_file:
      - .env
    command: python bot.py
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  api:
    build: .
    container_name: tg_quest_api
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    volumes:                             
      - backups_data:/backups
    command: sh -c "alembic upgrade head && uvicorn backend.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips='*'"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy


  nginx:
    image: nginx:alpine
    container_name: quest_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: quest_certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # СТАЛО (ports полностью удалены):
  db:
    image: postgres:15-alpine
    container_name: quest_postgresql
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "my_secure_password_2026"
      POSTGRES_DB: "quest_db"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - backups_data:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quest_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: quest_redis
    restart: always
    command: redis-server --appendonly yes --appendfsync everysec
    # Порты удалены! Теперь Redis доступен только для контейнеров внутри сети
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  pg_data:
  backups_data:
  redis_data:
  certbot_data:
  certbot_www:
