"""init_schema

Revision ID: c98ba924e75b
Revises: 
Create Date: 2026-06-22 19:13:22.600340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tgbot.database.models



# revision identifiers, used by Alembic.
revision: str = 'c98ba924e75b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('badge_emoji', sa.String(length=10), nullable=False),
    sa.Column('required_action', sa.String(length=50), nullable=False),
    sa.Column('required_value_bronze', sa.Integer(), nullable=True),
    sa.Column('required_value_silver', sa.Integer(), nullable=True),
    sa.Column('required_value_diamond', sa.Integer(), nullable=True),
    sa.Column('reward_coins_bronze', sa.Integer(), nullable=False),
    sa.Column('reward_coins_silver', sa.Integer(), nullable=False),
    sa.Column('reward_coins_diamond', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ar_markers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_ref_id', sa.String(length=250), nullable=True),
    sa.Column('model_url', sa.String(length=500), nullable=True),
    sa.Column('is_shard_collection', sa.Boolean(), nullable=False),
    sa.Column('shard_count', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ar_scan_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('challenge_type', sa.String(length=50), nullable=False),
    sa.Column('target_action', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_gems', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cheat_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('coop_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coop_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('craft_recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('result_item_name', sa.String(length=100), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('coins_cost', sa.Integer(), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_riddles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=100), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gem_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('telegram_payment_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('contribution_xp', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('emblem_emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('generates_income', sa.Boolean(), nullable=False),
    sa.Column('income_per_hour', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_slug'), 'items', ['slug'], unique=True)
    op.create_table('npc_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_id', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('dialogue_tree', sa.JSON(), nullable=True),
    sa.Column('drawflow_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('photo_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('photo_file_id', sa.String(length=250), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_location_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_location_logs_quest_id'), 'player_location_logs', ['quest_id'], unique=False)
    op.create_index(op.f('ix_player_location_logs_user_id'), 'player_location_logs', ['user_id'], unique=False)
    op.create_table('pvp_duels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('challenger_id', sa.BigInteger(), nullable=False),
    sa.Column('opponent_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('challenger_score', sa.Integer(), nullable=False),
    sa.Column('opponent_score', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('bet_coins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=100), nullable=False),
    sa.Column('wrong_answers', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_season_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('max_speed_kmh', sa.Float(), nullable=False),
    sa.Column('min_level_required', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('global_time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('is_coop', sa.Boolean(), nullable=False),
    sa.Column('coop_max_size', sa.Integer(), nullable=False),
    sa.Column('drawflow_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('random_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('coins_impact', sa.Integer(), nullable=False),
    sa.Column('karma_impact', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bonus_xp_multiplier', sa.Float(), nullable=False),
    sa.Column('bonus_coins_multiplier', sa.Float(), nullable=False),
    sa.Column('reward_item_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_id', sa.String(length=250), nullable=True),
    sa.Column('promo_pool_id', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('admin_response', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutorial_latitude', sa.Float(), nullable=False),
    sa.Column('tutorial_longitude', sa.Float(), nullable=False),
    sa.Column('tutorial_answer', sa.String(length=100), nullable=False),
    sa.Column('merchant_bonus', sa.Integer(), nullable=False),
    sa.Column('ranger_cd_minutes', sa.Integer(), nullable=False),
    sa.Column('historian_mult', sa.Float(), nullable=False),
    sa.Column('base_step_coins', sa.Integer(), nullable=False),
    sa.Column('base_step_score', sa.Integer(), nullable=False),
    sa.Column('quest_completion_bonus', sa.Integer(), nullable=False),
    sa.Column('karma_elixir_price', sa.Integer(), nullable=False),
    sa.Column('karma_elixir_effect', sa.Integer(), nullable=False),
    sa.Column('daily_gift_base_reward', sa.Integer(), nullable=False),
    sa.Column('daily_gift_increment', sa.Integer(), nullable=False),
    sa.Column('daily_gift_max_reward', sa.Integer(), nullable=False),
    sa.Column('scroll_event_price', sa.Integer(), nullable=False),
    sa.Column('scroll_event_karma', sa.Integer(), nullable=False),
    sa.Column('wallet_event_coins', sa.Integer(), nullable=False),
    sa.Column('wallet_event_karma_penalty', sa.Integer(), nullable=False),
    sa.Column('wallet_event_karma_reward', sa.Integer(), nullable=False),
    sa.Column('merc_lifetime_minutes', sa.Integer(), nullable=False),
    sa.Column('merc_summon_price', sa.Integer(), nullable=False),
    sa.Column('merc_efficiency', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('karma', sa.Integer(), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('rpg_class', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('max_weight_capacity', sa.Integer(), nullable=False),
    sa.Column('income_buffer', sa.Integer(), nullable=False),
    sa.Column('completed_tutorial', sa.Boolean(), nullable=False),
    sa.Column('cheat_warnings', sa.Integer(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('last_daily_at', sa.DateTime(), nullable=True),
    sa.Column('gift_streak', sa.Integer(), nullable=False),
    sa.Column('last_gift_at', sa.DateTime(), nullable=True),
    sa.Column('current_city_id', sa.Integer(), nullable=True),
    sa.Column('auto_city_detect', sa.Boolean(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('last_class_change', sa.DateTime(), nullable=True),
    sa.Column('global_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_tester', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_slug', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('generates_income', sa.Boolean(), nullable=False),
    sa.Column('income_per_hour', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_slug'], ['items.slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_time_seconds', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('is_season_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_progress_quest_id'), 'quest_progress', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_progress_user_id'), 'quest_progress', ['user_id'], unique=False)
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_slug', sa.String(length=100), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('generates_income', sa.Boolean(), nullable=False),
    sa.Column('income_per_hour', sa.Integer(), nullable=False),
    sa.Column('market_ids', sa.JSON(), nullable=True),
    sa.Column('buyback_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_slug'], ['items.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('instruction_text', sa.String(length=3000), nullable=False),
    sa.Column('welcome_message', sa.String(length=1200), nullable=True),
    sa.Column('history_info', sa.String(length=2000), nullable=True),
    sa.Column('photo_then_id', sa.String(length=250), nullable=True),
    sa.Column('photo_now_id', sa.String(length=250), nullable=True),
    sa.Column('audio_guide_id', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('is_night_only', sa.Boolean(), nullable=False),
    sa.Column('is_day_only', sa.Boolean(), nullable=False),
    sa.Column('weather_sun_only', sa.Boolean(), nullable=False),
    sa.Column('weather_rain_only', sa.Boolean(), nullable=False),
    sa.Column('weather_snow_only', sa.Boolean(), nullable=False),
    sa.Column('is_dry_only', sa.Boolean(), nullable=False),
    sa.Column('is_weather_only', sa.Boolean(), nullable=False),
    sa.Column('min_karma_required', sa.Integer(), nullable=False),
    sa.Column('required_flag', sa.String(length=50), nullable=True),
    sa.Column('granted_flag', sa.String(length=50), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('npc_name', sa.String(length=100), nullable=True),
    sa.Column('npc_dialogue', sa.JSON(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('branches', sa.JSON(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('required_item', sa.String(length=100), nullable=True),
    sa.Column('gives_item', sa.String(length=100), nullable=True),
    sa.Column('gives_item_chance', sa.Float(), nullable=False),
    sa.Column('secret_price', sa.Integer(), nullable=False),
    sa.Column('hint_1_delay', sa.Integer(), nullable=False),
    sa.Column('hint_1_text', sa.String(length=500), nullable=False),
    sa.Column('hint_2_delay', sa.Integer(), nullable=False),
    sa.Column('hint_2_text', sa.String(length=500), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_quest_id'), 'steps', ['quest_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('tier', sa.String(length=20), server_default='bronze', nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_table('active_quests',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('current_step_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(), nullable=False),
    sa.Column('step_activated_at', sa.DateTime(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('is_night_run', sa.Boolean(), nullable=False),
    sa.Column('is_rain_run', sa.Boolean(), nullable=False),
    sa.Column('current_npc_node', sa.String(length=50), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('frozen_accumulated_seconds', sa.Integer(), nullable=False),
    sa.Column('freeze_used', sa.Boolean(), nullable=False),
    sa.Column('is_maintenance_frozen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_game_message_id', sa.Integer(), nullable=True),
    sa.Column('prev_latitude', sa.Float(), nullable=True),
    sa.Column('prev_longitude', sa.Float(), nullable=True),
    sa.Column('prev_time', sa.DateTime(), nullable=True),
    sa.Column('pending_coins', sa.Integer(), nullable=False),
    sa.Column('pending_xp', sa.Integer(), nullable=False),
    sa.Column('pending_karma', sa.Integer(), nullable=False),
    sa.Column('pending_items', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['current_step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'quest_id')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('shop_item_id', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_codes')
    op.drop_table('active_quests')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_steps_quest_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_table('shop_items')
    op.drop_index(op.f('ix_quest_progress_user_id'), table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_quest_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    op.drop_table('inventory')
    op.drop_table('users')
    op.drop_table('user_challenges')
    op.drop_table('system_settings')
    op.drop_table('support_tickets')
    op.drop_table('sponsors')
    op.drop_table('seasons')
    op.drop_table('scheduled_broadcasts')
    op.drop_table('random_events')
    op.drop_table('quests')
    op.drop_table('quest_reviews')
    op.drop_table('quest_markets')
    op.drop_table('pvp_questions')
    op.drop_table('pvp_duels')
    op.drop_index(op.f('ix_player_location_logs_user_id'), table_name='player_location_logs')
    op.drop_index(op.f('ix_player_location_logs_quest_id'), table_name='player_location_logs')
    op.drop_table('player_location_logs')
    op.drop_table('photo_reports')
    op.drop_table('npc_characters')
    op.drop_index(op.f('ix_items_slug'), table_name='items')
    op.drop_table('items')
    op.drop_table('guilds')
    op.drop_table('guild_members')
    op.drop_table('global_events')
    op.drop_table('gem_transactions')
    op.drop_table('daily_riddles')
    op.drop_table('craft_recipes')
    op.drop_table('coop_sessions')
    op.drop_table('coop_members')
    op.drop_table('cities')
    op.drop_table('cheat_logs')
    op.drop_table('challenges')
    op.drop_table('ar_scan_logs')
    op.drop_table('ar_markers')
    op.drop_table('achievements')
    # ### end Alembic commands ###
